name: Project - Python sum
on:
  push:
    paths:
      - projects/python-simple/*
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: python3 projects/python-simple/test.py
